using CalamityFables.Content.Tiles.Graves;
using System.Text.RegularExpressions;
using Terraria.DataStructures;
using Terraria.Localization;
using Terraria.ObjectData;

namespace CalamityFables.Core
{
    public class GravestoneLoader : ModSystem
    {
        public static Mod Fables => CalamityFables.Instance;

        public static readonly List<List<int>> NormalVariants = new List<List<int>>();
        public static readonly List<List<int>> GoldVariants = new List<List<int>>();

        /// <summary>
        /// Loads a gravestone item and projectile with the given name and placement style
        /// Adds the loaded items and projectile instances into the provided lists.
        /// Be sure to call <see cref="ConfirmGravestones(int, List{AutoloadedGravestoneItem}, List{AutoloadedGravestoneProjectile}, bool)"/> during SetStaticDefaults to assign the place type of the tombstone to the items and projectiles
        /// </summary>
        /// <returns>The type of the loaded projectile instance</returns>
        public static int LoadGravestone(Mod mod, string gravestoneName, int placeStyle, string texturePath, List<AutoloadedGravestoneProjectile> projs, List<AutoloadedGravestoneItem> items)
        {
            AutoloadedGravestoneProjectile projectile = new AutoloadedGravestoneProjectile(gravestoneName, placeStyle, texturePath);
            mod.AddContent(projectile);

            AutoloadedGravestoneItem item = new AutoloadedGravestoneItem(gravestoneName, placeStyle, texturePath);
            mod.AddContent(item);

            projs.Add(projectile);
            items.Add(item);

            return projectile.Type;
        }

        /// <summary>
        /// Loads multiple gravestones at once
        /// </summary>
        /// <param name="projectileTypes">Filled with the list of projectile types that are generated. Use this as your random pool for dropping graves</param>
        /// <param name="projs">Gets filled with the list of projectile instances that are generated by the autoloader</param>
        /// <param name="items">Gets filled with the list of item instances that are generated by the autoloader</param>
        /// <param name="texturePath">The folder in which the sprites are found</param>
        /// <param name="names">The list of internal names for the gravestone items and projectiles. The internal names automatically get converted into pretty names for display purposes</param>
        public static void LoadGravestones(Mod mod, List<int> projectileTypes, List<AutoloadedGravestoneProjectile> projs, List<AutoloadedGravestoneItem> items, string texturePath, params string[] names)
        {
            int style = 0;
            foreach (string name in names)
            {
                projectileTypes.Add(LoadGravestone(mod, name, style, texturePath, projs, items));
                style++;
            }
        }

        /// <summary>
        /// This is necessary for the gravestones to load properly. This assigns the tile type to the item and projectile so they can place the correct grave type when used
        /// Also saves the graves in a special list for the purpose of shimmer cycling
        /// </summary>
        /// <param name="tileType"></param>
        /// <param name="items"></param>
        /// <param name="projectiles"></param>
        /// <param name="golden"></param>
        public static void ConfirmGravestones(int tileType, List<AutoloadedGravestoneItem> items, List<AutoloadedGravestoneProjectile> projectiles, bool golden = false)
        {
            //Assign the tile types
            foreach (AutoloadedGravestoneItem item in items)
                item.TileType = tileType;
            foreach (AutoloadedGravestoneProjectile projectile in projectiles)
                projectile.TileType = tileType;

            List<int> variantTypes = new List<int>();
            foreach (AutoloadedGravestoneItem grave in items.OrderBy(g => g.TileStyle))
                variantTypes.Add(grave.Type);

            if (golden)
                GoldVariants.Add(variantTypes);
            else
                NormalVariants.Add(variantTypes);

            //We don't need these anymore
            //Actually i want the items
            //items.Clear();
            projectiles.Clear();
        }

        public override void PostSetupContent()
        {
            for (int i = 0; i < NormalVariants.Count; i++)
            {
                for (int j = 0; j < 4; j++)
                {
                    int graveType = NormalVariants[i][j];
                    int nextGraveType = NormalVariants[(i + 1) % NormalVariants.Count][j];
                    ItemID.Sets.ShimmerTransformToItem[graveType] = nextGraveType;
                }
            }

            for (int i = 0; i < GoldVariants.Count; i++)
            {
                for (int j = 0; j < 4; j++)
                {
                    int graveType = GoldVariants[i][j];
                    int nextGraveType = GoldVariants[(i + 1) % GoldVariants.Count][j];
                    ItemID.Sets.ShimmerTransformToItem[graveType] = nextGraveType;
                }
            }
        }

        public override void Unload()
        {
            NormalVariants.Clear();
            GoldVariants.Clear();
        }
    }


    [Autoload(false)]
    public class AutoloadedGravestoneProjectile : ModProjectile
    {
        public override string Texture => TexturePath;
        public override string Name => InternalName != "" ? InternalName : base.Name;

        public string InternalName;
        public string TexturePath;
        public int TileType;
        public readonly int TileStyle;
        protected override bool CloneNewInstances => true;

        public override void SetStaticDefaults()
        {
            ProjectileID.Sets.IsAGravestone[Type] = true;
        }

        public override void SetDefaults()
        {
            Projectile.knockBack = 12f;
            Projectile.width = 24;
            Projectile.height = 24;
            Projectile.aiStyle = 17;
            Projectile.penetrate = -1;

            if (Main.getGoodWorld)
            {
                Projectile.friendly = true;
                Projectile.hostile = true;
            }
        }

        public AutoloadedGravestoneProjectile(string graveName, int tileStyle, string path)
        {
            InternalName = graveName + "Projectile";
            TileStyle = tileStyle;
            TexturePath = path + graveName;
        }

        //Litterally just copied from aistyle 17, but lets us set custom values
        public override bool PreAI()
        {
            if (Projectile.velocity.Y == 0f)
                Projectile.velocity.X *= 0.98f;

            Projectile.rotation += Projectile.velocity.X * 0.1f;
            Projectile.velocity.Y += 0.2f;
            if (Projectile.owner != Main.myPlayer)
                return false;

            int potentialPlacementX = (int)((Projectile.position.X + (Projectile.width / 2)) / 16f);
            int potentialPlacementY = (int)((Projectile.position.Y + Projectile.height - 4f) / 16f);
            bool placementSuccessful = false;

            TileObject objectData = default(TileObject);
            if (TileObject.CanPlace(potentialPlacementX, potentialPlacementY, TileType, TileStyle, Projectile.direction, out objectData))
                placementSuccessful = TileObject.Place(objectData);

            if (placementSuccessful)
            {
                NetMessage.SendObjectPlacement(-1, potentialPlacementX, potentialPlacementY, objectData.type, objectData.style, objectData.alternate, objectData.random, Projectile.direction);
                SoundEngine.PlaySound(SoundID.Dig, new Vector2(potentialPlacementX * 16, potentialPlacementY * 16));

                int signID = Sign.ReadSign(potentialPlacementX, potentialPlacementY);
                if (signID >= 0)
                {
                    Sign.TextSign(signID, Projectile.miscText);
                    NetMessage.SendData(MessageID.ReadSign, -1, -1, null, signID, 0f, (int)(byte)new BitsByte(b1: true));
                }

                Projectile.Kill();
            }
            return false;
        }
    }

    [Autoload(false)]
    public class AutoloadedGravestoneItem : ModItem
    {
        public override string Texture => TexturePath;
        public override string Name => InternalName != "" ? InternalName : base.Name;

        public string InternalName;
        public string TexturePath;
        public int TileType;
        public int TileStyle;
        protected override bool CloneNewInstances => true;

        public AutoloadedGravestoneItem(string graveName, int tileStyle, string path)
        {
            InternalName = graveName + "Item";
            TileStyle = tileStyle;
            TexturePath = path + graveName;
        }

        public override void SetDefaults()
        {
            Item.autoReuse = false;
            Item.useTurn = true;
            Item.useStyle = ItemUseStyleID.Swing;
            Item.useAnimation = 15;
            Item.rare = ItemRarityID.White;
            Item.useTime = 15;
            Item.maxStack = 9999;
            Item.consumable = true;
            Item.width = 30;
            Item.height = 44;
            Item.value = 0;
            Item.createTile = TileType;
            Item.placeStyle = TileStyle;
        }
    }

    [Autoload(false)]
    public class AutoloadedCrossmodGrave : BaseGrave
    {
        public override string Texture => TexturePath + InternalName;
        public override string Name => InternalName != "" ? InternalName : base.Name;

        private string InternalName;
        private string TexturePath;

        private int _dustType = 0;
        private bool _gilded = false;
        private Color _mapColor;
        private string[] _variantNames;


        private List<AutoloadedGravestoneItem> _items = new List<AutoloadedGravestoneItem>();
        private List<AutoloadedGravestoneProjectile> _projectiles = new List<AutoloadedGravestoneProjectile>();
        private List<int> _projectileTypes = new List<int>();

        public override Color MapColor => _mapColor;
        public override int BreakDust => _dustType;
        public override bool Glowing => false;
        public override bool Gilded => _gilded;

        public override List<AutoloadedGravestoneItem> Items => _items;
        public override List<AutoloadedGravestoneProjectile> Projectiles  => _projectiles;
        public override List<int> ProjectilePool => _projectileTypes;
        public override string DirectoryPath => TexturePath;
        public override string[] GravestoneNames => _variantNames;

        public AutoloadedCrossmodGrave(string graveName,  string path, bool gilded, int dustType, Color mapColor, string[] variantNames)
        {
            InternalName = graveName;
            TexturePath = path;
            _gilded = gilded;
            _dustType = dustType;
            _mapColor = mapColor;
            _variantNames = variantNames;
    }
    }
}
